# Generated by Django 6.0.6 on 2026-06-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_prompt_sent', models.TextField(blank=True, help_text="Prompt envoyé au moteur d'IA.")),
                ('ai_response_raw', models.TextField(blank=True, help_text="Réponse brute renvoyée par l'IA.")),
                ('ai_plan_structured', models.TextField(blank=True, help_text="Plan de voyage mis en forme pour l'affichage.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan IA',
                'verbose_name_plural': 'Plans IA',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, help_text='Image principale de la destination.', null=True, upload_to='destinations/')),
                ('tags', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules (ex: nature, famille, montagne).', max_length=255)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='BaseTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('trip_type', models.CharField(choices=[('family', 'Voyage en famille'), ('friends', 'Voyage entre amis'), ('couple', 'Voyage en couple'), ('solo', 'Voyage en solo')], default='family', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, help_text="Prix de base indiqué par l'admin.", max_digits=10)),
                ('min_days', models.PositiveIntegerField(default=1)),
                ('max_days', models.PositiveIntegerField(default=7)),
                ('default_tags', models.CharField(blank=True, help_text='Mots-clés par défaut pour ce voyage.', max_length=255)),
                ('description', models.TextField(help_text="Description générale du voyage (servira de contexte pour l'IA).")),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_trips', to='trips.destination')),
            ],
            options={
                'verbose_name': 'Voyage de base',
                'verbose_name_plural': 'Voyages de base',
            },
        ),
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Note de 1 à 5.')),
                ('text', models.TextField(blank=True)),
                ('user_suggested_price', models.DecimalField(blank=True, decimal_places=2, help_text="Prix estimé par l'utilisateur (optionnel).", max_digits=10, null=True)),
                ('approved_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.aitripplan')),
            ],
            options={
                'verbose_name': 'Avis de voyage',
                'verbose_name_plural': 'Avis de voyage',
            },
        ),
        migrations.CreateModel(
            name='UserTripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text="Nom ou pseudo de l'utilisateur.", max_length=100)),
                ('days', models.PositiveIntegerField(default=2)),
                ('people_adults', models.PositiveIntegerField(default=2)),
                ('people_children', models.PositiveIntegerField(default=0)),
                ('preferences', models.CharField(blank=True, help_text='Préférences séparées par des virgules (ex: nature, aventure, gastronomie).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_requests', to='trips.basetrip')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to='trips.destination')),
            ],
            options={
                'verbose_name': 'Demande de voyage',
                'verbose_name_plural': 'Demandes de voyage',
            },
        ),
        migrations.AddField(
            model_name='aitripplan',
            name='user_trip_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan', to='trips.usertriprequest'),
        ),
    ]
